export const SET_EMPLOYEE_DATA = 'SET_EMPLOYEE_DATA';
export const SET_PAYROLL_VIEW = 'SET_PAYROLL_VIEW';
export const SET_ADMIN_EMPLOYEE_DATA_VIEW = 'SET_ADMIN_EMPLOYEE_DATA_VIEW';
export const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';